node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('Build image') {
        sh "docker build --build-arg APP_NAME=nodejs -t 022539168230.dkr.ecr.us-east-1.amazonaws.com/solrsearch/:latest ."
    }
}
