node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://022539168230.dkr.ecr.us-east-2.amazonaws.com/john/', 'dockerhub') {
       def app = docker.build("fluidout/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
